#!/bin/sh

# build examples
cd examples
../node_modules/.bin/webpack --config webpack.config.production.js --progress --profile --colors
cd ..

# build dist
./node_modules/.bin/cjsx -cbo dist ./src/*.cjsx
./node_modules/.bin/cjsx -cbo dist ./src/*.coffee
# temp for .js file
./node_modules/.bin/babel ./src --out-dir ./dist

# build min dist
./node_modules/.bin/webpack
