#!/bin/sh

# checkout
git checkout master

# create a local gh-pages branch containing the splitted output folder
git subtree split --prefix examples -b gh-pages

# force the push of the gh-pages branch to the remote gh-pages branch at origin
git push -f origin gh-pages:gh-pages

# cleanup
git branch -D gh-pages
